DELETE FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE;
--INDV_N_1ST
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_INDV', INDV_N_1ST , 'INDV_N_1ST', NULL,NULL
FROM (
SELECT DISTINCT INDV_N_1ST FROM TCCMSMASK.TCCMS_INDV) A;
--INDV_N_LST
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_INDV', INDV_N_LST , 'INDV_N_LST', NULL,NULL
FROM (
SELECT DISTINCT INDV_N_LST FROM TCCMSMASK.TCCMS_INDV) A;
--INDV_N_MID
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_INDV', INDV_N_MID , 'INDV_N_MID', NULL,NULL
FROM (
SELECT DISTINCT INDV_N_MID FROM TCCMSMASK.TCCMS_INDV) A;
--INDV_C_SSN
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_INDV', INDV_C_SSN , 'INDV_C_SSN', NULL,NULL
FROM (
SELECT DISTINCT INDV_C_SSN  FROM TCCMSMASK.TCCMS_INDV) A;
--INDV_D_DOB
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_INDV', INDV_D_DOB , 'INDV_D_DOB', NULL,NULL
FROM (
SELECT DISTINCT INDV_D_DOB FROM TCCMSMASK.TCCMS_INDV) A;
--INDV_D_DOD
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_INDV', INDV_D_DOD , 'INDV_D_DOD', NULL,NULL
FROM (
SELECT DISTINCT INDV_D_DOD FROM TCCMSMASK.TCCMS_INDV) A;





--PRVN_N
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PENR', PRVN_N , 'PRVN_N', NULL,NULL
FROM (
SELECT DISTINCT PRVN_N FROM TCCMSMASK.TCCMS_PENR) A;

--PRVN_L_ADDR1
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PENR', PRVN_L_ADDR1 , 'PRVN_L_ADDR1', NULL,NULL
FROM (
SELECT DISTINCT PRVN_L_ADDR1 FROM TCCMSMASK.TCCMS_PENR) A;

--PRVN_L_ADDR2
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PENR', PRVN_L_ADDR2 , 'PRVN_L_ADDR2', NULL,NULL
FROM (
SELECT DISTINCT PRVN_L_ADDR2 FROM TCCMSMASK.TCCMS_PENR) A;

--PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PENR', ADDR,
'PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP', NULL,NULL
FROM (
SELECT DISTINCT RPAD(PRVN_L_CITY,18,' ')||RPAD(PRVN_L_ST,2,' ')||RPAD(PRVN_L_ZIP,10,' ') AS ADDR
FROM TCCMSMASK.TCCMS_PENR) A;



--PROV_N_CNTCT1_1ST
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV', PROV_N_CNTCT1_1ST , 'PROV_N_CNTCT1_1ST', NULL,NULL
FROM (
SELECT DISTINCT PROV_N_CNTCT1_1ST FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_N_CNTCT1_LST
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV', PROV_N_CNTCT1_LST , 'PROV_N_CNTCT1_LST', NULL,NULL
FROM (
SELECT DISTINCT PROV_N_CNTCT1_LST FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_N_CNTCT1_TITLE
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV', PROV_N_CNTCT1_TITLE , 'PROV_N_CNTCT1_TITLE', NULL,NULL
FROM (
SELECT DISTINCT PROV_N_CNTCT1_TITLE FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_N_BOARD_CHAIR
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV', PROV_N_BOARD_CHAIR , 'PROV_N_BOARD_CHAIR', NULL,NULL
FROM (
SELECT DISTINCT PROV_N_BOARD_CHAIR FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_L_MAIL_STRT
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV', PROV_L_MAIL_STRT , 'PROV_L_MAIL_STRT', NULL,NULL
FROM (
SELECT DISTINCT PROV_L_MAIL_STRT FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_L_MAIL_STRT2
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV', PROV_L_MAIL_STRT2 , 'PROV_L_MAIL_STRT2', NULL,NULL
FROM (
SELECT DISTINCT PROV_L_MAIL_STRT2 FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_L_MAIL_CITY,PROV_L_MAIL_ST,PROV_L_MAIL_ZIP
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV', ADDR, 
'PROV_L_MAIL_CITY,PROV_L_MAIL_ST,PROV_L_MAIL_ZIP', NULL,NULL
FROM (
SELECT DISTINCT RPAD(PROV_L_MAIL_CITY,18,' ')||RPAD(PROV_L_MAIL_ST,2,' ')||RPAD(PROV_L_MAIL_ZIP,10,' ') AS ADDR
FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_L_PH
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV', PROV_L_PH , 'PROV_L_PH', NULL,NULL
FROM (
SELECT DISTINCT PROV_L_PH FROM TCCMSMASK.TCCMS_PROV) A;

--PRRP_N_PAYEE
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRRP', PRRP_N_PAYEE , 'PRRP_N_PAYEE', NULL,NULL
FROM (
SELECT DISTINCT PRRP_N_PAYEE FROM TCCMSMASK.TCCMS_PRRP) A;



--PRVN_L_ADDR1
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRVN', PRVN_L_ADDR1 , 'PRVN_L_ADDR1', NULL,NULL
FROM (
SELECT DISTINCT PRVN_L_ADDR1 FROM TCCMSMASK.TCCMS_PRVN) A;

--PRVN_L_ADDR2
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRVN', PRVN_L_ADDR2 , 'PRVN_L_ADDR2', NULL,NULL
FROM (
SELECT DISTINCT PRVN_L_ADDR2 FROM TCCMSMASK.TCCMS_PRVN) A;

--PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRVN', ADDR,
'PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP', NULL,NULL
FROM (
SELECT DISTINCT RPAD(PRVN_L_CITY,18,' ')||RPAD(PRVN_L_ST,2,'')||RPAD(PRVN_L_ZIP,10,' ') AS ADDR FROM TCCMSMASK.TCCMS_PRVN) A;


--CCIN_N_PROV
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CCIN', CCIN_N_PROV , 'CCIN_N_PROV', NULL,NULL
FROM (
SELECT DISTINCT CCIN_N_PROV FROM TCCMSMASK.TCCMS_CCIN) A;

--CASE_L_RES_STRT
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO', CASE_L_RES_STRT , 'CASE_L_RES_STRT', NULL,NULL
FROM (
SELECT DISTINCT CASE_L_RES_STRT FROM TCCMSMASK.TCCMS_CASE_DEMO) A;

--CASE_L_RES_STRT2
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO', CASE_L_RES_STRT2 , 'CASE_L_RES_STRT2', NULL,NULL
FROM (
SELECT DISTINCT CASE_L_RES_STRT2 FROM TCCMSMASK.TCCMS_CASE_DEMO) A;

--CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO', ADDR,
 'CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4', NULL,NULL
FROM (
SELECT DISTINCT RPAD(CASE_L_RES_CITY,18,' ')||RPAD(CASE_L_RES_ST,2,' ')||CASE_L_RES_ZIP5||CASE_L_RES_ZIP4 AS ADDR
FROM TCCMSMASK.TCCMS_CASE_DEMO) A;



--CASE_L_MAIL_STRT
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO', CASE_L_MAIL_STRT , 'CASE_L_MAIL_STRT', NULL,NULL
FROM (
SELECT DISTINCT CASE_L_MAIL_STRT FROM TCCMSMASK.TCCMS_CASE_DEMO) A;

--CASE_L_MAIL_STRT2
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO', CASE_L_MAIL_STRT2 , 'CASE_L_MAIL_STRT2', NULL,NULL
FROM (
SELECT DISTINCT CASE_L_MAIL_STRT2 FROM TCCMSMASK.TCCMS_CASE_DEMO) A;

--CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO', ADDR,
'CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4', NULL,NULL
FROM (
SELECT DISTINCT RPAD(CASE_L_MAIL_CITY,18,' ')||RPAD(CASE_L_MAIL_ST,2,' ')||CASE_L_MAIL_ZIP5||CASE_L_MAIL_ZIP4 AS ADDR
FROM TCCMSMASK.TCCMS_CASE_DEMO) A;



--CASE_L_EMAIL
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO', CASE_L_EMAIL , 'CASE_L_EMAIL', NULL,NULL
FROM (
SELECT DISTINCT CASE_L_EMAIL FROM TCCMSMASK.TCCMS_CASE_DEMO) A;

--CASE_L_OTH_PH_AREA,CASE_L_OTH_PH_PRF,CASE_L_OTH_PH_SFX
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO',PHN,
'CASE_L_OTH_PH_AREA,CASE_L_OTH_PH_PRF,CASE_L_OTH_PH_SFX', NULL,NULL
FROM (
SELECT DISTINCT CASE_L_OTH_PH_AREA|| CASE_L_OTH_PH_PRF||CASE_L_OTH_PH_SFX AS PHN FROM TCCMSMASK.TCCMS_CASE_DEMO) A;


--CASE_L_RES_PH_AREA,CASE_L_RES_PH_PRF,CASE_L_RES_PH_SFX
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO',  PHN ,
'CASE_L_RES_PH_AREA,CASE_L_RES_PH_PRF,CASE_L_RES_PH_SFX', NULL,NULL
FROM (
SELECT DISTINCT CASE_L_RES_PH_AREA|| CASE_L_RES_PH_PRF||CASE_L_RES_PH_SFX AS PHN FROM TCCMSMASK.TCCMS_CASE_DEMO) A;


--CASE_L_WORK_PH_AREA,CASE_L_WORK_PH_PRF,CASE_L_WORK_PH_SFX
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CASE_DEMO',PHN,
'CASE_L_WORK_PH_AREA,CASE_L_WORK_PH_PRF,CASE_L_WORK_PH_SFX', NULL,NULL
FROM (
SELECT DISTINCT CASE_L_WORK_PH_AREA||CASE_L_WORK_PH_PRF||CASE_L_WORK_PH_SFX as PHN FROM TCCMSMASK.TCCMS_CASE_DEMO) A;

INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PROV) A;

INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRVN',PRVN_C,'PRVN_C', NULL,NULL
FROM (
SELECT DISTINCT PRVN_C FROM TCCMSMASK.TCCMS_PRVN) A;


/*
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_CHEN',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_CHEN) A;


INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PENR',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PENR) A;


INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PENR',PRVN_C,'PRVN_C', NULL,NULL
FROM (
SELECT DISTINCT PRVN_C FROM TCCMSMASK.TCCMS_PENR) A;


INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRCL',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PRCL) A;


INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV',PRVN_C,'PRVN_C', NULL,NULL
FROM (
SELECT DISTINCT PRVN_C FROM TCCMSMASK.TCCMS_PROV) A;





INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV_STAR',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PROV_STAR) A;


INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRRA',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PRRA) A;


INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRRD',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PRRD) A;


INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRRG',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PRRG) A;


INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRRP',PRVN_C,'PRVN_C', NULL,NULL
FROM (
SELECT DISTINCT PRVN_C FROM TCCMSMASK.TCCMS_PRRP) A;





INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRCN',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PRCN) A;

INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PVFE',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PVFE) A;


INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PRRP',PROV_C,'PROV_C', NULL,NULL
FROM (
SELECT DISTINCT PROV_C FROM TCCMSMASK.TCCMS_PRRP) A;


--PROV_N
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV',PROV_N,'PROV_N', NULL,NULL
FROM (
SELECT DISTINCT PROV_N FROM TCCMSMASK.TCCMS_PROV) A;
*/

--PROV_L_STRT
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV',PROV_L_STRT,'PROV_L_STRT', NULL,NULL
FROM (
SELECT DISTINCT PROV_L_STRT FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_L_STRT2
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV',PROV_L_STRT2,'PROV_L_STRT2', NULL,NULL
FROM (
SELECT DISTINCT PROV_L_STRT2 FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_L_CITY,PROV_L_ST,PROV_L_ZIP
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV', ADDR, 
'PROV_L_CITY,PROV_L_ST,PROV_L_ZIP', NULL,NULL
FROM (
SELECT DISTINCT RPAD(PROV_L_CITY,18,' ')||RPAD(PROV_L_ST,2,' ')||RPAD(PROV_L_ZIP,10,' ') AS ADDR
FROM TCCMSMASK.TCCMS_PROV) A;

--PROV_C_EMAIL
INSERT INTO TCCMSMASK.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,ORIGINAL,TYPE,MASK_KEY,MASKED)
SELECT 'TCCMS_PROV',PROV_C_EMAIL,'PROV_C_EMAIL', NULL,NULL
FROM (
SELECT DISTINCT PROV_C_EMAIL FROM TCCMSMASK.TCCMS_PROV) A;

DELETE  FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE WHERE ORIGINAL IS NULL;

