START TRANSACTION

--INDV_N_1ST
UPDATE TCCMSMASK.TCCMS_INDV A SET A.INDV_N_1ST = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.INDV_N_1ST
 AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_N_1ST'
 and rownum=1
) 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.INDV_N_1ST AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_N_1ST');

--INDV_N_LST
UPDATE TCCMSMASK.TCCMS_INDV A SET A.INDV_N_LST = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.INDV_N_LST
 AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_N_LST'
 and rownum=1
) 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.INDV_N_LST AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_N_LST');


--INDV_D_DOB
UPDATE  TCCMSMASK.TCCMS_INDV A SET A.INDV_D_DOB = (SELECT to_date(B.MASKED,'DD-MM-YYYY')
FROM 
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE B.original = A.INDV_D_DOB
 AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_D_DOB'
  and rownum=1
) 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.INDV_D_DOB AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_D_DOB');


--INDV_D_DOD
UPDATE  TCCMSMASK.TCCMS_INDV A SET A.INDV_D_DOD = (SELECT to_date(B.MASKED,'DD-MM-YYYY') FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE B.original = A.INDV_D_DOD
 AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_D_DOD'
 and rownum=1
) 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.INDV_D_DOD AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_D_DOD');

/*
--INDV_C_SSN
UPDATE TCCMSMASK.TCCMS_INDV A SET A.INDV_C_SSN = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.INDV_C_SSN
 AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_C_SSN'
) 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.INDV_C_SSN AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_C_SSN');
*/
--INDV_N_MID
UPDATE TCCMSMASK.TCCMS_INDV A SET A.INDV_N_MID = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.INDV_N_MID
 AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_N_MID'
 and rownum=1
) 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.INDV_N_MID AND B.TABLE_NAME = 'TCCMS_INDV'  AND  B.TYPE='INDV_N_MID');

--PRVN_N
UPDATE TCCMSMASK.TCCMS_PENR A SET A.PRVN_N = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRVN_N
 AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_N'
) 
WHERE A.PRVN_N IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRVN_N AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_N');

--PRVN_L_ADDR1
UPDATE TCCMSMASK.TCCMS_PENR A SET A.PRVN_L_ADDR1 = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRVN_L_ADDR1
 AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_ADDR1'
) 
WHERE A.PRVN_L_ADDR1 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRVN_L_ADDR1 AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_ADDR1');

--PRVN_L_ADDR2
UPDATE TCCMSMASK.TCCMS_PENR A SET A.PRVN_L_ADDR2 = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRVN_L_ADDR2
 AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_ADDR2'
 and rownum=1
) 
WHERE A.PRVN_L_ADDR2 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRVN_L_ADDR2 AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_ADDR2');

--PRVN_L_CITY
UPDATE TCCMSMASK.TCCMS_PENR A SET (A.PRVN_L_CITY, A.PRVN_L_ST, A.PRVN_L_ZIP) = 
(SELECT LTRIM(RTRIM(SUBSTR(B.MASKED,1,18))),LTRIM(RTRIM(SUBSTR(B.MASKED,19,2))),LTRIM(RTRIM(SUBSTR(B.MASKED,21,10))) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.PRVN_L_CITY AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.PRVN_L_ST 
  AND NVL(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,10))),1) = NVL(A.PRVN_L_ZIP,1))
 AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP'
 and rownum=1
) 
WHERE  EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.PRVN_L_CITY AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.PRVN_L_ST 
AND NVL(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,10))),1) = NVL(A.PRVN_L_ZIP,1))
 AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP');

/*--PRVN_L_ST
UPDATE TCCMSMASK.TCCMS_PENR A SET A.PRVN_L_ST = (SELECT SUBSTR(B.MASKED,19,2) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,19,2) = A.PRVN_L_ST
 AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP'
 and rownum=1
) 
WHERE A.PRVN_L_ST IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,19,2) = A.PRVN_L_ST AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP');
--PRVN_L_ZIP
UPDATE TCCMSMASK.TCCMS_PENR A SET A.PRVN_L_ZIP = (SELECT SUBSTR(B.MASKED,21,10) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,21,10) = A.PRVN_L_ZIP
 AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP'
 and rownum=1
) 
WHERE A.PRVN_L_ZIP IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,21,10) = A.PRVN_L_ZIP AND B.TABLE_NAME = 'TCCMS_PENR'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP');
*/
--PROV_N_CNTCT1_1ST
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_N_CNTCT1_1ST = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_N_CNTCT1_1ST
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N_CNTCT1_1ST'
 and rownum=1
) 
WHERE A.PROV_N_CNTCT1_1ST IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_N_CNTCT1_1ST AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N_CNTCT1_1ST');

--PROV_N_CNTCT1_LST
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_N_CNTCT1_LST = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_N_CNTCT1_LST
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N_CNTCT1_LST'
 and rownum=1
) 
WHERE A.PROV_N_CNTCT1_LST IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_N_CNTCT1_LST AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N_CNTCT1_LST');

--PROV_L_MAIL_STRT2
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_L_MAIL_STRT2 = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_L_MAIL_STRT2
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_STRT2'
 and rownum=1
) 
WHERE A.PROV_L_MAIL_STRT2 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_L_MAIL_STRT2 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_STRT2');

--PROV_L_MAIL_STRT
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_L_MAIL_STRT = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_L_MAIL_STRT
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_STRT'
 and rownum=1
) 
WHERE A.PROV_L_MAIL_STRT IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_L_MAIL_STRT AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_STRT');

--PROV_N_BOARD_CHAIR
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_N_BOARD_CHAIR = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_N_BOARD_CHAIR
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N_BOARD_CHAIR'
 and rownum=1
) 
WHERE A.PROV_N_BOARD_CHAIR IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_N_BOARD_CHAIR AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N_BOARD_CHAIR');

--PROV_N_CNTCT1_TITLE
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_N_CNTCT1_TITLE = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_N_CNTCT1_TITLE
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N_CNTCT1_TITLE'
 and rownum=1
) 
WHERE A.PROV_N_CNTCT1_TITLE IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_N_CNTCT1_TITLE AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N_CNTCT1_TITLE');

--PROV_L_MAIL_CITY
UPDATE TCCMSMASK.TCCMS_PROV A SET (A.PROV_L_MAIL_CITY,A.PROV_L_MAIL_ST,A.PROV_L_MAIL_ZIP) = 
(SELECT LTRIM(RTRIM(SUBSTR(B.MASKED,1,18))),LTRIM(RTRIM(SUBSTR(B.MASKED,19,2))),LTRIM(RTRIM(SUBSTR(B.MASKED,21,10))) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  
  (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.PROV_L_MAIL_CITY AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.PROV_L_MAIL_ST 
  AND NVL(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,10))),1) = NVL(A.PROV_L_MAIL_ZIP,1))
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_CITY,PROV_L_MAIL_ST,PROV_L_MAIL_ZIP'
 and rownum=1
) 
WHERE  EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.PROV_L_MAIL_CITY AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.PROV_L_MAIL_ST 
AND NVL(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,10))),1) = NVL(A.PROV_L_MAIL_ZIP,1))
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_CITY,PROV_L_MAIL_ST,PROV_L_MAIL_ZIP');

 
 /*--PROV_L_MAIL_ST
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_L_MAIL_ST = (SELECT SUBSTR(B.MASKED,19,2) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,19,2) = A.PROV_L_MAIL_ST
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_CITY,PROV_L_MAIL_ST,PROV_L_MAIL_ZIP'
 and rownum=1
) 
WHERE A.PROV_L_MAIL_ST IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,19,2) = A.PROV_L_MAIL_ST AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_CITY,PROV_L_MAIL_ST,PROV_L_MAIL_ZIP');
--PROV_L_MAIL_ZIP
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_L_MAIL_ZIP = (SELECT SUBSTR(B.MASKED,21,10) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,21,10) = A.PROV_L_MAIL_ZIP
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_CITY,PROV_L_MAIL_ST,PROV_L_MAIL_ZIP'
 and rownum=1
) 
WHERE A.PROV_L_MAIL_ZIP IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,21,10) = A.PROV_L_MAIL_ZIP AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_MAIL_CITY,PROV_L_MAIL_ST,PROV_L_MAIL_ZIP');
*/
--PROV_L_PH
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_L_PH = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_L_PH
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_PH'
 and rownum=1
) 
WHERE A.PROV_L_PH IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_L_PH AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_PH');

--PRRP_N_PAYEE
UPDATE TCCMSMASK.TCCMS_PRRP A SET A.PRRP_N_PAYEE = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRRP_N_PAYEE
 AND B.TABLE_NAME = 'TCCMS_PRRP'  AND  B.TYPE='PRRP_N_PAYEE'
 and rownum=1
) 
WHERE A.PRRP_N_PAYEE IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRRP_N_PAYEE AND B.TABLE_NAME = 'TCCMS_PRRP'  AND  B.TYPE='PRRP_N_PAYEE');

--PRVN_L_ADDR1
UPDATE TCCMSMASK.TCCMS_PRVN A SET A.PRVN_L_ADDR1 = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRVN_L_ADDR1
 AND B.TABLE_NAME = 'TCCMS_PRVN'  AND  B.TYPE='PRVN_L_ADDR1'
 and rownum=1
) 
WHERE A.PRVN_L_ADDR1 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRVN_L_ADDR1 AND B.TABLE_NAME = 'TCCMS_PRVN'  AND  B.TYPE='PRVN_L_ADDR1');

--PRVN_L_ADDR2
UPDATE TCCMSMASK.TCCMS_PRVN A SET A.PRVN_L_ADDR2 = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRVN_L_ADDR2
 AND B.TABLE_NAME = 'TCCMS_PRVN'  AND  B.TYPE='PRVN_L_ADDR2'
 and rownum=1
) 
WHERE A.PRVN_L_ADDR2 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRVN_L_ADDR2 AND B.TABLE_NAME = 'TCCMS_PRVN'  AND  B.TYPE='PRVN_L_ADDR2');

--PRVN_L_CITY
UPDATE TCCMSMASK.TCCMS_PRVN A SET (A.PRVN_L_CITY,A.PRVN_L_ST,A.PRVN_L_ZIP) = 
(SELECT LTRIM(RTRIM(SUBSTR(B.MASKED,1,18))),LTRIM(RTRIM(SUBSTR(B.MASKED,19,2))),LTRIM(RTRIM(SUBSTR(B.MASKED,21,10))) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.PRVN_L_CITY AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.PRVN_L_ST 
  AND NVL(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,10))),1) = NVL(LTRIM(RTRIM(A.PRVN_L_ZIP)),1))
 --AND B.TABLE_NAME = 'TCCMS_PRVN'  
 AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP'
 and rownum=1
) 
WHERE  EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.PRVN_L_CITY AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.PRVN_L_ST 
AND NVL(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,10))),1) = NVL(LTRIM(RTRIM(A.PRVN_L_ZIP)),1))
--AND B.TABLE_NAME = 'TCCMS_PRVN' 
AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP');

/*
--PRVN_L_ST
UPDATE TCCMSMASK.TCCMS_PRVN A SET A.PRVN_L_ST = (SELECT SUBSTR(B.MASKED,19,2) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,19,2) = A.PRVN_L_ST
 AND B.TABLE_NAME = 'TCCMS_PRVN'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP'
 and rownum=1
) 
WHERE A.PRVN_L_ST IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,19,2) = A.PRVN_L_ST AND B.TABLE_NAME = 'TCCMS_PRVN'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP');
--PRVN_L_ZIP
UPDATE TCCMSMASK.TCCMS_PRVN A SET A.PRVN_L_ZIP = (SELECT SUBSTR(B.MASKED,21,10) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,21,10) = A.PRVN_L_ZIP
 AND B.TABLE_NAME = 'TCCMS_PRVN'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP'
 and rownum=1
) 
WHERE A.PRVN_L_ZIP IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,21,10) = A.PRVN_L_ZIP AND B.TABLE_NAME = 'TCCMS_PRVN'  AND  B.TYPE='PRVN_L_CITY,PRVN_L_ST,PRVN_L_ZIP');
*/
--CCIN_N_PROV
UPDATE TCCMSMASK.TCCMS_CCIN A SET A.CCIN_N_PROV = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.CCIN_N_PROV
 AND B.TABLE_NAME = 'TCCMS_CCIN'  AND  B.TYPE='CCIN_N_PROV'
 and rownum=1
) 
WHERE A.CCIN_N_PROV IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.CCIN_N_PROV AND B.TABLE_NAME = 'TCCMS_CCIN'  AND  B.TYPE='CCIN_N_PROV');

--CASE_L_RES_STRT
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_RES_STRT = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.CASE_L_RES_STRT
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_STRT'
 and rownum=1
) 
WHERE A.CASE_L_RES_STRT IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.CASE_L_RES_STRT AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_STRT');

--CASE_L_RES_STRT2
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_RES_STRT2 = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.CASE_L_RES_STRT2
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_STRT2'
 and rownum=1
) 
WHERE A.CASE_L_RES_STRT2 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.CASE_L_RES_STRT2 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_STRT2');

--CASE_L_EMAIL
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_EMAIL = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.CASE_L_EMAIL
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_EMAIL'
 and rownum=1
) 
WHERE A.CASE_L_EMAIL IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.CASE_L_EMAIL AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_EMAIL');

--PROV_C_EMAIL
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_C_EMAIL = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C_EMAIL
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_C_EMAIL'
 and rownum=1
) 
WHERE A.PROV_C_EMAIL IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C_EMAIL AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_C_EMAIL');


--CASE_L_MAIL_STRT
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_MAIL_STRT = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.CASE_L_MAIL_STRT
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_STRT'
 and rownum=1
) 
WHERE A.CASE_L_MAIL_STRT IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.CASE_L_MAIL_STRT AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_STRT');


--CASE_L_MAIL_STRT2
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_MAIL_STRT2 = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.CASE_L_MAIL_STRT2
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_STRT2'
 and rownum=1
) 
WHERE A.CASE_L_MAIL_STRT2 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.CASE_L_MAIL_STRT2 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_STRT2');

--CASE_L_RES_CITY
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET (A.CASE_L_RES_CITY, A.CASE_L_RES_ST,A.CASE_L_RES_ZIP5,A.CASE_L_RES_ZIP4) = 
(SELECT LTRIM(RTRIM(SUBSTR(B.MASKED,1,18))) ,LTRIM(RTRIM(SUBSTR(B.MASKED,19,2))),
TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.MASKED,21,5)))),TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.MASKED,26,4))))
FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.CASE_L_RES_CITY 
		 AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.CASE_L_RES_ST 
         AND TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,5)))) = A.CASE_L_RES_ZIP5 
         AND NVL(TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,26,4)))),1) = NVL(A.CASE_L_RES_ZIP4,1))
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4'
 and rownum=1
) 
WHERE A.CASE_L_RES_CITY IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.CASE_L_RES_CITY 
		 AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.CASE_L_RES_ST 
         AND TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,5)))) = A.CASE_L_RES_ZIP5 
         AND NVL(TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,26,4)))),1) = NVL(A.CASE_L_RES_ZIP4,1))
AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  
AND  B.TYPE='CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4');

/*
--CASE_L_RES_ST
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_RES_ST = (SELECT SUBSTR(B.MASKED,19,2) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,19,2) = A.CASE_L_RES_ST
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4'
 and rownum=1
) 
WHERE A.CASE_L_RES_ST IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,19,2) = A.CASE_L_RES_ST AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4');

--CASE_L_RES_ZIP5
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_RES_ZIP5 = (SELECT SUBSTR(B.MASKED,21,5) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,21,5) = A.CASE_L_RES_ZIP5
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4'
 and rownum=1
) 
WHERE A.CASE_L_RES_ZIP5 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,21,5) = A.CASE_L_RES_ZIP5 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4');

--CASE_L_RES_ZIP4
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_RES_ZIP4 = (SELECT SUBSTR(B.MASKED,26,4) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,26,4) = A.CASE_L_RES_ZIP4
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4'
 and rownum=1
) 
WHERE A.CASE_L_RES_ZIP4 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,26,4) = A.CASE_L_RES_ZIP4 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4');

*/

--CASE_L_MAIL_CITY
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET (A.CASE_L_MAIL_CITY,A.CASE_L_MAIL_ST,A.CASE_L_MAIL_ZIP5,A.CASE_L_MAIL_ZIP4) = 
(SELECT LTRIM(RTRIM(SUBSTR(B.MASKED,1,18))),LTRIM(RTRIM(SUBSTR(B.MASKED,19,2))),
TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.MASKED,21,5)))),TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.MASKED,26,4)))) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.CASE_L_MAIL_CITY 
  AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.CASE_L_MAIL_ST 
  AND TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,5)))) = A.CASE_L_MAIL_ZIP5 
  AND NVL(TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,26,4)))),1) = NVL(A.CASE_L_MAIL_ZIP4,1))
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4'
 and rownum=1) 
WHERE A.CASE_L_MAIL_CITY IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE (     LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.CASE_L_MAIL_CITY 
            AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.CASE_L_MAIL_ST 
            AND TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,5)))) = A.CASE_L_MAIL_ZIP5 
            AND NVL(TO_NUMBER(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,26,4)))),1) = NVL(A.CASE_L_MAIL_ZIP4,1))
AND  B.TABLE_NAME = 'TCCMS_CASE_DEMO' 
AND B.TYPE='CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4');

/*
--CASE_L_MAIL_ST
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_MAIL_ST = (SELECT SUBSTR(B.MASKED,19,2) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,19,2) = A.CASE_L_MAIL_ST
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4'
 and rownum=1
) 
WHERE A.CASE_L_MAIL_ST IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,19,2) = A.CASE_L_MAIL_ST AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4');

--CASE_L_MAIL_ZIP5
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_MAIL_ZIP5 = (SELECT SUBSTR(B.MASKED,21,5) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,21,5) = A.CASE_L_MAIL_ZIP5
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4'
 and rownum=1
) 
WHERE A.CASE_L_MAIL_ZIP5 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,21,5) = A.CASE_L_MAIL_ZIP5 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4');

--CASE_L_MAIL_ZIP4
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_MAIL_ZIP4 = (SELECT SUBSTR(B.MASKED,26,4) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,26,4) = A.CASE_L_MAIL_ZIP4
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4'
 and rownum=1
) 
WHERE A.CASE_L_MAIL_ZIP4 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,26,4) = A.CASE_L_MAIL_ZIP4 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4');
*/

--CASE_L_OTH_PH_AREA
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET (A.CASE_L_OTH_PH_AREA,A.CASE_L_OTH_PH_PRF,A.CASE_L_OTH_PH_SFX) = 
(SELECT TO_NUMBER(SUBSTR(B.MASKED,1,3)),TO_NUMBER(SUBSTR(B.MASKED,4,3)),TO_NUMBER(SUBSTR(B.MASKED,7,4)) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  (SUBSTR(B.ORIGINAL,1,3) = A.CASE_L_OTH_PH_AREA AND SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_OTH_PH_PRF AND SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_OTH_PH_SFX)
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_OTH_PH_AREA,CASE_L_OTH_PH_PRF,CASE_L_OTH_PH_SFX'
 and rownum=1
) 
WHERE  EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE (SUBSTR(B.ORIGINAL,1,3) = A.CASE_L_OTH_PH_AREA AND SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_OTH_PH_PRF AND SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_OTH_PH_SFX)
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_OTH_PH_AREA,CASE_L_OTH_PH_PRF,CASE_L_OTH_PH_SFX');
/*--CASE_L_OTH_PH_PRF
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_OTH_PH_PRF = (SELECT SUBSTR(B.MASKED,4,3) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_OTH_PH_PRF
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_OTH_PH_AREA,CASE_L_OTH_PH_PRF,CASE_L_OTH_PH_SFX'
 and rownum=1
) 
WHERE A.CASE_L_OTH_PH_PRF IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_OTH_PH_PRF AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_OTH_PH_AREA,CASE_L_OTH_PH_PRF,CASE_L_OTH_PH_SFX');
--CASE_L_OTH_PH_SFX
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_OTH_PH_SFX = (SELECT SUBSTR(B.MASKED,7,4) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_OTH_PH_SFX
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_OTH_PH_AREA,CASE_L_OTH_PH_PRF,CASE_L_OTH_PH_SFX'
 and rownum=1
) 
WHERE A.CASE_L_OTH_PH_SFX IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_OTH_PH_SFX AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_OTH_PH_AREA,CASE_L_OTH_PH_PRF,CASE_L_OTH_PH_SFX');
*/

--CASE_L_RES_PH_AREA
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET (A.CASE_L_RES_PH_AREA,A.CASE_L_RES_PH_PRF,A.CASE_L_RES_PH_SFX) = 
(SELECT TO_NUMBER(SUBSTR(B.MASKED,1,3)),TO_NUMBER(SUBSTR(B.MASKED,4,3)),TO_NUMBER(SUBSTR(B.MASKED,7,4)) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  (SUBSTR(B.ORIGINAL,1,3) = A.CASE_L_RES_PH_AREA AND SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_RES_PH_PRF AND SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_RES_PH_SFX)
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_PH_AREA,CASE_L_RES_PH_PRF,CASE_L_RES_PH_SFX'
 and rownum=1
) 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE (SUBSTR(B.ORIGINAL,1,3) = A.CASE_L_RES_PH_AREA AND SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_RES_PH_PRF AND SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_RES_PH_SFX)
AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_PH_AREA,CASE_L_RES_PH_PRF,CASE_L_RES_PH_SFX');
/*--CASE_L_RES_PH_PRF
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_RES_PH_PRF = (SELECT SUBSTR(B.MASKED,4,3) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_RES_PH_PRF
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_PH_AREA,CASE_L_RES_PH_PRF,CASE_L_RES_PH_SFX'
 and rownum=1
) 
WHERE A.CASE_L_RES_PH_PRF IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_RES_PH_PRF AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_PH_AREA,CASE_L_RES_PH_PRF,CASE_L_RES_PH_SFX');
--CASE_L_RES_PH_SFX
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_RES_PH_SFX = (SELECT SUBSTR(B.MASKED,7,4) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_RES_PH_SFX
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_PH_AREA,CASE_L_RES_PH_PRF,CASE_L_RES_PH_SFX'
 and rownum=1
) 
WHERE A.CASE_L_RES_PH_SFX IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_RES_PH_SFX AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_RES_PH_AREA,CASE_L_RES_PH_PRF,CASE_L_RES_PH_SFX');
*/

--CASE_L_WORK_PH_AREA
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET (A.CASE_L_WORK_PH_AREA,A.CASE_L_WORK_PH_PRF,A.CASE_L_WORK_PH_SFX) = 
(SELECT TO_NUMBER(SUBSTR(B.MASKED,1,3)),TO_NUMBER(SUBSTR(B.MASKED,4,3)),TO_NUMBER(SUBSTR(B.MASKED,7,4)) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  (SUBSTR(B.ORIGINAL,1,3) = A.CASE_L_WORK_PH_AREA AND SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_WORK_PH_PRF AND SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_WORK_PH_SFX)
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_WORK_PH_AREA,CASE_L_WORK_PH_PRF,CASE_L_WORK_PH_SFX'
 and rownum=1
) 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE (SUBSTR(B.ORIGINAL,1,3) = A.CASE_L_WORK_PH_AREA AND SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_WORK_PH_PRF AND SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_WORK_PH_SFX)
AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_WORK_PH_AREA,CASE_L_WORK_PH_PRF,CASE_L_WORK_PH_SFX');

/*--CASE_L_WORK_PH_PRF
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_WORK_PH_PRF = (SELECT SUBSTR(B.MASKED,4,3) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_WORK_PH_PRF
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_WORK_PH_AREA,CASE_L_WORK_PH_PRF,CASE_L_WORK_PH_SFX'
 and rownum=1
) 
WHERE A.CASE_L_WORK_PH_PRF IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,4,3) = A.CASE_L_WORK_PH_PRF AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_WORK_PH_AREA,CASE_L_WORK_PH_PRF,CASE_L_WORK_PH_SFX');


--CASE_L_WORK_PH_SFX
UPDATE TCCMSMASK.TCCMS_CASE_DEMO A SET A.CASE_L_WORK_PH_SFX = (SELECT SUBSTR(B.MASKED,7,4) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_WORK_PH_SFX
 AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_WORK_PH_AREA,CASE_L_WORK_PH_PRF,CASE_L_WORK_PH_SFX'
 and rownum=1
) 
WHERE A.CASE_L_WORK_PH_SFX IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE SUBSTR(B.ORIGINAL,7,4) = A.CASE_L_WORK_PH_SFX AND B.TABLE_NAME = 'TCCMS_CASE_DEMO'  AND  B.TYPE='CASE_L_WORK_PH_AREA,CASE_L_WORK_PH_PRF,CASE_L_WORK_PH_SFX');
*/

UPDATE TCCMSMASK.TCCMS_CHEN A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PENR A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PENR A SET A.PRVN_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRVN_C AND B.TYPE='PRVN_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PRVN') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRVN_C AND B.TABLE_NAME = 'TCCMS_PRVN' AND B.TYPE='PRVN_C');


UPDATE TCCMSMASK.TCCMS_PRCL A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PRCN A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PROV_STAR A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C'  and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PROV A SET A.PRVN_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRVN_C AND B.TYPE='PRVN_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PRVN') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRVN_C AND B.TABLE_NAME = 'TCCMS_PRVN' AND B.TYPE='PRVN_C');


UPDATE TCCMSMASK.TCCMS_PRRA A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PRRD A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PRRG A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PRRP A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');


UPDATE TCCMSMASK.TCCMS_PRRP A SET A.PRVN_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRVN_C AND B.TYPE='PRVN_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PRVN') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRVN_C AND B.TABLE_NAME = 'TCCMS_PRVN' AND B.TYPE='PRVN_C');


UPDATE TCCMSMASK.TCCMS_PRVN A SET A.PRVN_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PRVN_C AND B.TYPE='PRVN_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PRVN') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PRVN_C AND B.TABLE_NAME = 'TCCMS_PRVN' AND B.TYPE='PRVN_C');


UPDATE TCCMSMASK.TCCMS_PVFE A SET A.PROV_C = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_C AND B.TYPE='PROV_C' and rownum=1 AND B.TABLE_NAME = 'TCCMS_PROV') 
WHERE EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_C AND B.TABLE_NAME = 'TCCMS_PROV' AND B.TYPE='PROV_C');

/*
--PROV_N
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_N = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_N
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N'
 and rownum=1
) 
WHERE A.PROV_N IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_N AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_N');
*/

--PROV_L_STRT
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_L_STRT = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_L_STRT
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_STRT'
 and rownum=1
) 
WHERE A.PROV_L_STRT IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_L_STRT AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_STRT');

--PROV_L_STRT2
UPDATE TCCMSMASK.TCCMS_PROV A SET A.PROV_L_STRT2 = (SELECT B.MASKED FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  B.ORIGINAL = A.PROV_L_STRT2
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_STRT2'
 and rownum=1
) 
WHERE A.PROV_L_STRT2 IS NOT NULL AND EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE B.ORIGINAL = A.PROV_N AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_STRT2');

--PROV_L_CITY,PROV_L_ST,PROV_L_ZIP
UPDATE TCCMSMASK.TCCMS_PROV A SET (A.PROV_L_CITY,A.PROV_L_ST,A.PROV_L_ZIP) = 
(SELECT LTRIM(RTRIM(SUBSTR(B.MASKED,1,18))),LTRIM(RTRIM(SUBSTR(B.MASKED,19,2))),LTRIM(RTRIM(SUBSTR(B.MASKED,21,10))) FROM
  TCCMSMASK.TCCMS_MASK_DTL_TABLE B
  WHERE  (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.PROV_L_CITY 
  AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.PROV_L_ST 
  AND NVL(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,10))),1) = NVL(A.PROV_L_ZIP,1))
 AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_CITY,PROV_L_ST,PROV_L_ZIP'
 and rownum=1
) 
WHERE  EXISTS(SELECT 1 FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE B 
WHERE (LTRIM(RTRIM(SUBSTR(B.ORIGINAL,1,18))) = A.PROV_L_CITY 
AND LTRIM(RTRIM(SUBSTR(B.ORIGINAL,19,2))) = A.PROV_L_ST 
AND NVL(LTRIM(RTRIM(SUBSTR(B.ORIGINAL,21,10))),1) = NVL(A.PROV_L_ZIP,1)) 
AND B.TABLE_NAME = 'TCCMS_PROV'  AND  B.TYPE='PROV_L_CITY,PROV_L_ST,PROV_L_ZIP');



/*
--DI
SELECT PRVN_C_SEQ FROM PRELAND.TCCMS_PROV PROV
WHERE PROV_C<> PRVN_C
AND EXISTS (SELECT 1 FROM PRELAND.TCCMS_PROV P WHERE PROV.PRVN_C_SEQ =P.PRVN_C_SEQ AND P.PROV_C=P.PRVN_C)

DELETE FROM PRELAND.TCCMS_MASK_DTL_TABLE;

INSERT INTO PRELAND.TCCMS_MASK_DTL_TABLE
(TABLE_NAME,TYPE,ORIGINAL,MASK_KEY,MASKED)
SELECT
TABLE_NAME,TYPE,ORIGINAL,MASK_KEY,MASKED
FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE;

DELETE FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE;
*/
UPDATE TCCMSMASK.TCCMS_PROV A
SET A.PROV_L_PH_ALT = MASKED_PHN.NEXTVAL 
WHERE A.PROV_L_PH_ALT IS NOT NULL

--COMMIT
--rollback