Changed database context to 'ie_ie_cnv'.
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_DEATHVRF_MV')CREATE synonym dbo.RT_DEATHVRF_MV FOR iewp_ie_dev4.dbo.RT_DEATHVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_CITIZENSTATUSVRF_MV')CREATE synonym dbo.RT_CITIZENSTATUSVRF_MV FOR iewp_ie_dev4.dbo.RT_CITIZENSTATUSVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_HIGHESTLEVELEDU_MV')CREATE synonym dbo.RT_HIGHESTLEVELEDU_MV FOR iewp_ie_dev4.dbo.RT_HIGHESTLEVELEDU_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_HOUSEHOLDVRF_MV')CREATE synonym dbo.RT_HOUSEHOLDVRF_MV FOR iewp_ie_dev4.dbo.RT_HOUSEHOLDVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_CASEMODE_MV')CREATE synonym dbo.RT_CASEMODE_MV FOR iewp_ie_dev4.dbo.RT_CASEMODE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_RELATIONTYPE_MV')CREATE synonym dbo.RT_RELATIONTYPE_MV FOR iewp_ie_dev4.dbo.RT_RELATIONTYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_JBTYPE_MV')CREATE synonym dbo.RT_JBTYPE_MV FOR iewp_ie_dev4.dbo.RT_JBTYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_EDTOA_MV')CREATE synonym dbo.RT_EDTOA_MV FOR iewp_ie_dev4.dbo.RT_EDTOA_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_PRGRS_MV')CREATE synonym dbo.RT_PRGRS_MV FOR iewp_ie_dev4.dbo.RT_PRGRS_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_SNPWRKRG_MV')CREATE synonym dbo.RT_SNPWRKRG_MV FOR iewp_ie_dev4.dbo.RT_SNPWRKRG_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_MARITALSTATUS_MV')CREATE synonym dbo.RT_MARITALSTATUS_MV FOR iewp_ie_dev4.dbo.RT_MARITALSTATUS_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_IDVERIFICATION_MV')CREATE synonym dbo.RT_IDVERIFICATION_MV FOR iewp_ie_dev4.dbo.RT_IDVERIFICATION_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_RESIDENCYVERF_MV')CREATE synonym dbo.RT_RESIDENCYVERF_MV FOR iewp_ie_dev4.dbo.RT_RESIDENCYVERF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_EDEXCLRSN_MV')CREATE synonym dbo.RT_EDEXCLRSN_MV FOR iewp_ie_dev4.dbo.RT_EDEXCLRSN_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_EDINCLRSN_MV')CREATE synonym dbo.RT_EDINCLRSN_MV FOR iewp_ie_dev4.dbo.RT_EDINCLRSN_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_MJSVCD_MV')CREATE synonym dbo.RT_MJSVCD_MV FOR iewp_ie_dev4.dbo.RT_MJSVCD_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_FITREASON_MV')CREATE synonym dbo.RT_FITREASON_MV FOR iewp_ie_dev4.dbo.RT_FITREASON_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_EXMPTN_MV')CREATE synonym dbo.RT_EXMPTN_MV FOR iewp_ie_dev4.dbo.RT_EXMPTN_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_FITAPRELATION_MV')CREATE synonym dbo.RT_FITAPRELATION_MV FOR iewp_ie_dev4.dbo.RT_FITAPRELATION_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_INCLSN_MV')CREATE synonym dbo.RT_INCLSN_MV FOR iewp_ie_dev4.dbo.RT_INCLSN_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_INITIALENTRYDATEVRF')CREATE synonym dbo.RT_INITIALENTRYDATEVRF FOR iewp_ie_dev4.dbo.RT_INITIALENTRYDATEVRFGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_INITIALENTRYDATEVRF_MV')CREATE synonym dbo.RT_INITIALENTRYDATEVRF_MV FOR iewp_ie_dev4.dbo.RT_INITIALENTRYDATEVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_DISABILITYCRI_MV')CREATE synonym dbo.RT_DISABILITYCRI_MV FOR iewp_ie_dev4.dbo.RT_DISABILITYCRI_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_PROGRAM_MV')CREATE synonym dbo.RT_PROGRAM_MV FOR iewp_ie_dev4.dbo.RT_PROGRAM_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_ISSUANCETYPE_MV')CREATE synonym dbo.RT_ISSUANCETYPE_MV FOR iewp_ie_dev4.dbo.RT_ISSUANCETYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_BENEFITSTATUSCODE_MV')CREATE synonym dbo.RT_BENEFITSTATUSCODE_MV FOR iewp_ie_dev4.dbo.RT_BENEFITSTATUSCODE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_ALIENSTATUS_MV')CREATE synonym dbo.RT_ALIENSTATUS_MV FOR iewp_ie_dev4.dbo.RT_ALIENSTATUS_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_PARIND_MV')CREATE synonym dbo.RT_PARIND_MV FOR iewp_ie_dev4.dbo.RT_PARIND_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_ACTTYPE_MV')CREATE synonym dbo.RT_ACTTYPE_MV FOR iewp_ie_dev4.dbo.RT_ACTTYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_UNEARNEDINCOMETYPE_MV')CREATE synonym dbo.RT_UNEARNEDINCOMETYPE_MV FOR iewp_ie_dev4.dbo.RT_UNEARNEDINCOMETYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_ETNONCOMPREA_MV')CREATE synonym dbo.RT_ETNONCOMPREA_MV FOR iewp_ie_dev4.dbo.RT_ETNONCOMPREA_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_SNAPVIOTYPE_MV')CREATE synonym dbo.RT_SNAPVIOTYPE_MV FOR iewp_ie_dev4.dbo.RT_SNAPVIOTYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_MEDICALEXPENSETYPE_MV')CREATE synonym dbo.RT_MEDICALEXPENSETYPE_MV FOR iewp_ie_dev4.dbo.RT_MEDICALEXPENSETYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_LIQUIDRESOURCETYPE_MV')CREATE synonym dbo.RT_LIQUIDRESOURCETYPE_MV FOR iewp_ie_dev4.dbo.RT_LIQUIDRESOURCETYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_UNEARNEDINCOMEVRF_MV')CREATE synonym dbo.RT_UNEARNEDINCOMEVRF_MV FOR iewp_ie_dev4.dbo.RT_UNEARNEDINCOMEVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_DEPENDENTEXPTYPE_MV')CREATE synonym dbo.RT_DEPENDENTEXPTYPE_MV FOR iewp_ie_dev4.dbo.RT_DEPENDENTEXPTYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_EARNEDINCTYPE_MV')CREATE synonym dbo.RT_EARNEDINCTYPE_MV FOR iewp_ie_dev4.dbo.RT_EARNEDINCTYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_LIQUIDRESOURCEVRF_MV')CREATE synonym dbo.RT_LIQUIDRESOURCEVRF_MV FOR iewp_ie_dev4.dbo.RT_LIQUIDRESOURCEVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_SHELTEREXPENSEVRF_MV')CREATE synonym dbo.RT_SHELTEREXPENSEVRF_MV FOR iewp_ie_dev4.dbo.RT_SHELTEREXPENSEVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_PAYEXPFREQUENCY_MV')CREATE synonym dbo.RT_PAYEXPFREQUENCY_MV FOR iewp_ie_dev4.dbo.RT_PAYEXPFREQUENCY_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_EDREASONCD_MV')CREATE synonym dbo.RT_EDREASONCD_MV FOR iewp_ie_dev4.dbo.RT_EDREASONCD_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_LAJETSTATUSCODE_MV')CREATE synonym dbo.RT_LAJETSTATUSCODE_MV FOR iewp_ie_dev4.dbo.RT_LAJETSTATUSCODE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_TIMELIMIT_MV')CREATE synonym dbo.RT_TIMELIMIT_MV FOR iewp_ie_dev4.dbo.RT_TIMELIMIT_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_INCOMEDOCTYPE_MV')CREATE synonym dbo.RT_INCOMEDOCTYPE_MV FOR iewp_ie_dev4.dbo.RT_INCOMEDOCTYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_ACTNAME_MV')CREATE synonym dbo.RT_ACTNAME_MV FOR iewp_ie_dev4.dbo.RT_ACTNAME_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_EARNEDINCVRF_MV')CREATE synonym dbo.RT_EARNEDINCVRF_MV FOR iewp_ie_dev4.dbo.RT_EARNEDINCVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_PROGRAMSTATUS_MV')CREATE synonym dbo.RT_PROGRAMSTATUS_MV FOR iewp_ie_dev4.dbo.RT_PROGRAMSTATUS_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_SHELTEREXPENSETYPE_MV')CREATE synonym dbo.RT_SHELTEREXPENSETYPE_MV FOR iewp_ie_dev4.dbo.RT_SHELTEREXPENSETYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_BISTATUSCODE_MV')CREATE synonym dbo.RT_BISTATUSCODE_MV FOR iewp_ie_dev4.dbo.RT_BISTATUSCODE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_EDETREGIND_MV')CREATE synonym dbo.RT_EDETREGIND_MV FOR iewp_ie_dev4.dbo.RT_EDETREGIND_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_HLEDUCMPLTD_MV')CREATE synonym dbo.RT_HLEDUCMPLTD_MV FOR iewp_ie_dev4.dbo.RT_HLEDUCMPLTD_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_WORKREGCODE_MV')CREATE synonym dbo.RT_WORKREGCODE_MV FOR iewp_ie_dev4.dbo.RT_WORKREGCODE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_STATE_MV')CREATE synonym dbo.RT_STATE_MV FOR iewp_ie_dev4.dbo.RT_STATE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_RACEDISPLAY_MV')CREATE synonym dbo.RT_RACEDISPLAY_MV FOR iewp_ie_dev4.dbo.RT_RACEDISPLAY_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_RESIDENTVRF_MV')CREATE synonym dbo.RT_RESIDENTVRF_MV FOR iewp_ie_dev4.dbo.RT_RESIDENTVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_BIREASONCODE_MV')CREATE synonym dbo.RT_BIREASONCODE_MV FOR iewp_ie_dev4.dbo.RT_BIREASONCODE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_PARISH_MV')CREATE synonym dbo.RT_PARISH_MV FOR iewp_ie_dev4.dbo.RT_PARISH_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_LIVINGARRANGEMENTYPE_MV')CREATE synonym dbo.RT_LIVINGARRANGEMENTYPE_MV FOR iewp_ie_dev4.dbo.RT_LIVINGARRANGEMENTYPE_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_LIVINGARRANGEMENTVRF_MV')CREATE synonym dbo.RT_LIVINGARRANGEMENTVRF_MV FOR iewp_ie_dev4.dbo.RT_LIVINGARRANGEMENTVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_DOBVRF_MV')CREATE synonym dbo.RT_DOBVRF_MV FOR iewp_ie_dev4.dbo.RT_DOBVRF_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_ETHNICITY_MV')CREATE synonym dbo.RT_ETHNICITY_MV FOR iewp_ie_dev4.dbo.RT_ETHNICITY_MVGo
IF NOT EXISTS (SELECT 1 FROM FROM ie_ie_cnv.SYS.synonyms WHERE NAME = 'RT_GENDER_MV')CREATE synonym dbo.RT_GENDER_MV FOR iewp_ie_dev4.dbo.RT_GENDER_MVGo
