SELECT DISTINCT
  A.IE_CASE_NUM AS 'IE LACAP Case Number'
, C.MEM_NAME_FIRST+' '+C.MEM_NAME_LAST AS 'IE LACAP HOH Name'
, C.MEM_PID AS 'IE LACAP HOH Person ID'
, A.LEGACY_CASE_NUM AS 'LAMI LACAP Case ID'
, C.MEM_NAME_FIRST+' '+C.MEM_NAME_LAST AS 'IE SNAP/TANF HOH Name'
, COUNT(DISTINCT A.IE_CASE_NUM) AS 'Distinct Count of IE Cases'
, COUNT(DISTINCT A.LEGACY_CASE_NUM) AS 'Count of LAMI Cases'
FROM [LAND].[CNV_CASE_MERGE_SPLIT] A
INNER JOIN LAND.LAMI_CASE B ON A.IE_CASE_NUM=B.CASE_CID
INNER JOIN LAND.LAMI_MEMBER C ON B.CASE_PID=C.MEM_PID
WHERE SPLIT_MERGE_IND = 'M'
GROUP BY A.IE_CASE_NUM 
, C.MEM_NAME_FIRST+' '+C.MEM_NAME_LAST 
, C.MEM_PID 
, A.LEGACY_CASE_NUM
ORDER BY A.IE_CASE_NUM