SELECT COUNT(1), TYPE FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE 
GROUP BY TYPE
ORDER BY 1 DESC;


select * from  TCCMSMASK.TCCMS_MASK_DTL_TABLE where masked = original
and type in ('INDV_D_DOB','INDV_D_DOD');

SELECT * FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE where masked = original
AND TYPE IN ('INDV_N_1ST' , 'INDV_N_LST');

SELECT * FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE where masked = original
AND TYPE IN ('INDV_N_1ST' , 'INDV_N_LST');

SELECT * FROM TCCMSMASK.TCCMS_MASK_DTL_TABLE where masked = original
AND TYPE IN (
'CASE_L_RES_STRT2',
'CASE_L_MAIL_STRT2',
'CASE_L_MAIL_CITY,CASE_L_MAIL_ST,CASE_L_MAIL_ZIP5,CASE_L_MAIL_ZIP4',
'CASE_L_RES_CITY,CASE_L_RES_ST,CASE_L_RES_ZIP5,CASE_L_RES_ZIP4');






