SELECT 
A.DATA_CONVERSION_HEADER_ID DATA_CONVERSION_HEADER_ID, 
'LAMI' SYSTEM_CODE,
LEGACY_FILE_NAME, isnull(LSD_DATA_EXTRACT_COUNT,0) as Table_Count,
--INVALID_Cnt
isnull(INVALID_Cnt,0) as INVALID_Cnt
FROM [CONV_ADMIN].[DCM_LEGACY_EXTRACT_DETAIL] A
LEFT JOIN (
SELECT  DATA_CONVERSION_HEADER_ID,
LANDING_TABLE_NAME,
COUNT(PRIMARY_KEY_VALUE) AS INVALID_Cnt
FROM [CONV_ADMIN].[DCM_PRELANDING_TABLE_PROFILING] 
--WHERE DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
GROUP BY LANDING_TABLE_NAME, DATA_CONVERSION_HEADER_ID

) B ON B.DATA_CONVERSION_HEADER_ID=A.DATA_CONVERSION_HEADER_ID AND LEGACY_FILE_NAME = LANDING_TABLE_NAME
WHERE A.DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
AND EXISTS (SELECT 1 FROM CONV_ADMIN.DCM_LANDING_MASTER_TABLES B  Where CONVERSION_REQUIRED_IND = 'Y' AND LANDING_TABLE_NAME = LEGACY_FILE_NAME)
AND LEFT(LEGACY_FILE_NAME,4) = 'LAMI'

UNION 

SELECT 
A.DATA_CONVERSION_HEADER_ID, 
'JAS' SYSTEM_CODE,
LEGACY_FILE_NAME, isnull(LSD_DATA_EXTRACT_COUNT,0) as Table_Count,
INVALID_Cnt
FROM [CONV_ADMIN].[DCM_LEGACY_EXTRACT_DETAIL] A
LEFT JOIN (
SELECT  DATA_CONVERSION_HEADER_ID,
LANDING_TABLE_NAME,
COUNT(PRIMARY_KEY_VALUE) AS INVALID_Cnt
FROM [CONV_ADMIN].[DCM_PRELANDING_TABLE_PROFILING] 
--WHERE DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
GROUP BY LANDING_TABLE_NAME, DATA_CONVERSION_HEADER_ID

) B ON B.DATA_CONVERSION_HEADER_ID=A.DATA_CONVERSION_HEADER_ID AND LEGACY_FILE_NAME = LANDING_TABLE_NAME
WHERE A.DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
AND EXISTS (SELECT 1 FROM CONV_ADMIN.DCM_LANDING_MASTER_TABLES B  Where CONVERSION_REQUIRED_IND = 'Y' AND LANDING_TABLE_NAME = LEGACY_FILE_NAME)
AND LEFT(LEGACY_FILE_NAME,3) = 'JAS'

 
UNION 

SELECT 
A.DATA_CONVERSION_HEADER_ID, 
'AP' SYSTEM_CODE,
LEGACY_FILE_NAME, isnull(LSD_DATA_EXTRACT_COUNT,0) as Table_Count,
INVALID_Cnt
FROM [CONV_ADMIN].[DCM_LEGACY_EXTRACT_DETAIL] A
LEFT JOIN (
SELECT  DATA_CONVERSION_HEADER_ID,
LANDING_TABLE_NAME,
COUNT(PRIMARY_KEY_VALUE) AS INVALID_Cnt
FROM [CONV_ADMIN].[DCM_PRELANDING_TABLE_PROFILING] 
--WHERE DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
GROUP BY LANDING_TABLE_NAME, DATA_CONVERSION_HEADER_ID

) B ON B.DATA_CONVERSION_HEADER_ID=A.DATA_CONVERSION_HEADER_ID AND LEGACY_FILE_NAME = LANDING_TABLE_NAME
WHERE A.DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
AND EXISTS (SELECT 1 FROM CONV_ADMIN.DCM_LANDING_MASTER_TABLES B  Where CONVERSION_REQUIRED_IND = 'Y' AND LANDING_TABLE_NAME = LEGACY_FILE_NAME)
AND LEFT(LEGACY_FILE_NAME,2) = 'AP'