SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].[LEGACY_DP_LAMI_MEMBER]
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].[LEGACY_DP_ELIGIBILITY]
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_JAS_JB_CASE
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_JAS_JB_COMP_TRACKING
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,COUNT(CID) as 'Distinct Cases'
,'' as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_JAS_JB_PAYMENT_HISTORY
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_JB_COMPONENT
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_JB_MEMBER_BANKING
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(AP_PG_PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_ABSENT_PARENT
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_ASSET_RESOURCES
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,COUNT(CID) as 'Distinct Cases'
,'' as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_BENEFIT_ISSUE
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,COUNT(CID) as 'Distinct Cases'
,'' as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_CASE
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,COUNT(CID) as 'Distinct Cases'
,'' as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_CASE_ADDRESS
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,COUNT(CID) as 'Distinct Cases'
,'' as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_CASE_PROGRAM
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,COUNT(CLAIM_CID) as 'Distinct Cases'
,'' as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_CLAIM
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_DEATHFILE
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_DOC_IMPRISONED_DRUG_OFFENSE
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_EXPENSES
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,COUNT(CID) as 'Distinct Cases'
,'' as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_HOH
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_INCOME_EARNED
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_INCOME_SPECIAL
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_INCOME_UNEARNED
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_LACAP_SDX
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_LIMITS
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_SANCTIONS
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION
UNION ALL
SELECT DISTINCT
TABLE_NAME as 'Source File Name'
,ISSUE_COLUMN_NAME as 'Field Name'
,'' as 'Error Code'
,PROFILE_DESCRIPTION as 'Failure Reason'
,COUNT(PROFILING_ID) AS 'Error Count'
,'' as 'Distinct Cases'
,COUNT(PID) as 'Distinct Persons'
FROM [DPROFILE].LEGACY_DP_LAMI_SANCTIONS
GROUP BY PROFILING_ID, TABLE_NAME, ISSUE_COLUMN_NAME, PROFILE_DESCRIPTION