SELECT
	[DCM_LEGACY_RECON_DETAIL_IECV301_ID] DCM_LEGACY_RECON_DETAIL_IECV301_ID,
	[DATA_CONVERSION_HEADER_ID] DATA_CONVERSION_HEADER_ID,
	[SYSTEM_CODE] SYSTEM_CODE,
	[NO_OF_LEGACY_CLIENTS_EXTRACTED] NO_OF_LEGACY_CLIENTS_EXTRACTED,
	[NO_OF_LEGACY_CLIENTS_FAILED_VALIDATION] NO_OF_LEGACY_CLIENTS_FAILED_VALIDATION,
	[NO_OF_IE_CLIENTS_EXTRACTED] NO_OF_IE_CLIENTS_EXTRACTED,
	[NO_OF_LEGACY_CLIENTS_MATCHED] NO_OF_LEGACY_CLIENTS_MATCHED,
	[Run_Date] Run_Date
FROM [CONV_ADMIN].[DCM_LEGACY_RECON_DETAIL_IECV301] (NOLOCK)
ORDER BY  [DCM_LEGACY_RECON_DETAIL_IECV301_ID],[SYSTEM_CODE]