SELECT
	[DCM_LEGACY_RECON_DETAIL_IECV303_ID] DCM_LEGACY_RECON_DETAIL_IECV303_ID,
	[DATA_CONVERSION_HEADER_ID] DATA_CONVERSION_HEADER_ID,
	[TYPE_OF_ISSUANCE] TYPE_OF_ISSUANCE,
	[NO_OF_ISSUANCE_RECEIVED] NO_OF_ISSUANCE_RECEIVED,
	[NO_OF_ISSUANCE_CONVERTED] NO_OF_ISSUANCE_CONVERTED,
	[TOTAL_ISSUANCE_AMOUNT_RECEIVED] TOTAL_ISSUANCE_AMOUNT_RECEIVED,
	[TOTAL_ISSUANCE_AMOUNT_CONVERTED] TOTAL_ISSUANCE_AMOUNT_CONVERTED,
	[Run_Date] Run_Date
FROM [CONV_ADMIN].[DCM_LEGACY_RECON_DETAIL_IECV303] (NOLOCK)	
ORDER BY  [DCM_LEGACY_RECON_DETAIL_IECV303_ID], [TYPE_OF_ISSUANCE]