SELECT
    [DCM_LEGACY_RECON_DETAIL_IECV305_ID] DCM_LEGACY_RECON_DETAIL_IECV305_ID,
	[DATA_CONVERSION_HEADER_ID] DATA_CONVERSION_HEADER_ID,
	[ITEM_TYPE] ITEM_TYPE,
	[LAMI_CLIENT_COUNT] LAMI_CLIENT_COUNT,
	[CONVERTED_CLIENT_COUNT] CONVERTED_CLIENT_COUNT,
	[Run_Date] Run_Date
FROM [CONV_ADMIN].[DCM_LEGACY_RECON_DETAIL_IECV305](NOLOCK)
ORDER BY  [DCM_LEGACY_RECON_DETAIL_IECV305_ID]