SELECT
	[DCM_LEGACY_RECON_DETAIL_IECV304_ID] DCM_LEGACY_RECON_DETAIL_IECV304_ID,
	[DATA_CONVERSION_HEADER_ID] DATA_CONVERSION_HEADER_ID,
	[SANCTION_TYPE] SANCTION_TYPE,
	[LAMI_SANCTIONED_CLIENTS_COUNT] LAMI_SANCTIONED_CLIENTS_COUNT,
	[CONVERTED_SANCTIONED_CLIENTS_COUNT] CONVERTED_SANCTIONED_CLIENTS_COUNT,
	[Run_Date] Run_Date
FROM [CONV_ADMIN].[DCM_LEGACY_RECON_DETAIL_IECV304] (NOLOCK)
ORDER BY  [DCM_LEGACY_RECON_DETAIL_IECV304_ID], [SANCTION_TYPE]