SELECT 
	[DCM_LEGACY_RECON_DETAIL_IECV302_ID] 	DCM_LEGACY_RECON_DETAIL_IECV302_ID,
	[DATA_CONVERSION_HEADER_ID] DATA_CONVERSION_HEADER_ID,
	[SYSTEM_CODE] SYSTEM_CODE,
	[NO_OF_ACTIVE_CASES_EXTRACTED] NO_OF_ACTIVE_CASES_EXTRACTED,
	[NO_OF_CLOSED_CASES_EXTRACTED] NO_OF_CLOSED_CASES_EXTRACTED,
	[NO_OF_LAMI_CASES_CONVERTED] NO_OF_LAMI_CASES_CONVERTED,
	[NO_OF_IE_CASES_CREATED] NO_OF_IE_CASES_CREATED,
	[Run_Date] Run_Date
FROM [CONV_ADMIN].[DCM_LEGACY_RECON_DETAIL_IECV302] (NOLOCK)	
ORDER BY  [DCM_LEGACY_RECON_DETAIL_IECV302_ID],[SYSTEM_CODE]