SELECT 
B.LANDING_FILE_GROUP AS GROUP_NAME ,
A.LANDING_TABLE_NAME,
B.LANDING_DATA_EXTRACT_DATE AS EXTRACT_DATE,
A.VALIDATION_DESC,
COUNT(1) AS COUNT
FROM [CONV_ADMIN].[DCM_PRELANDING_TABLE_PROFILING] A
LEFT JOIN [CONV_ADMIN].[DCM_LANDING_EXTRACT_DETAIL] B ON A.LANDING_TABLE_NAME=B.LANDING_TABLE_NAME
WHERE ERROR_IND = 'Y'
and A.DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
and B.DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
GROUP BY B.LANDING_FILE_GROUP,A.LANDING_TABLE_NAME,B.LANDING_DATA_EXTRACT_DATE,A.VALIDATION_DESC
ORDER BY GROUP_NAME, EXTRACT_DATE DESC