SELECT 
B.TARGET_GROUP_NAME AS GROUP_NAME ,
A.STAGING_TABLE_NAME,
B.TSD_DATA_EXTRACT_DATE AS EXTRACT_DATE,
A.VALIDATION_DESC,
COUNT(1) AS COUNT
FROM [CONV_ADMIN].[DCM_STAGING_TABLE_PROFILING] A
inner JOIN [CONV_ADMIN].[DCM_STAGING_EXTRACT_DETAIL] B ON A.STAGING_TABLE_NAME=B.TARGET_TABLE_NAME
WHERE ERROR_IND = 'Y'
and B.DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
and A.DATA_CONVERSION_HEADER_ID = dbo.F_GET_HDR_ID()
GROUP BY B.TARGET_GROUP_NAME,A.STAGING_TABLE_NAME,B.TSD_DATA_EXTRACT_DATE,A.VALIDATION_DESC
ORDER BY GROUP_NAME, EXTRACT_DATE DESC